In [68]:
import pandas as pd

In [69]:
preguntas = pd.read_excel("data/libro-de-codigos-emse-2018-corregido.xlsx")
df = pd.read_csv("data/EMSE_DatosAbiertos.csv")

In [70]:
codigos.head()

,Código variable standard,Código variable ARG (Nº de pregunta),Pregunta,Códigos de respuesta,Etiquetas de respuesta
5,q1,q1,¿Qué edad tienes?,1.0,11 años o menos
6,q1,q1,¿Qué edad tienes?,2.0,12 años
7,q1,q1,¿Qué edad tienes?,3.0,13 años
8,q1,q1,¿Qué edad tienes?,4.0,14 años
9,q1,q1,¿Qué edad tienes?,5.0,15 años

In [71]:
preguntas = preguntas.iloc[4:].dropna(how="all")  # Eliminamos filas vacias

columnas_para_propagar = ["Código variable standard", "Código variable ARG (Nº de pregunta)", "Pregunta"]
preguntas[columnas_para_propagar] = preguntas[columnas_para_propagar].ffill()  # Completamos los valores nulos vacios de las filas siguientes

# Eliminamos encabezados de cada pregunta
mask = (
    preguntas["Códigos de respuesta"].isna()
    & preguntas["Etiquetas de respuesta"].isna()
    & preguntas["Código variable standard"].duplicated(keep=False)
)

preguntas = preguntas[~mask]

In [78]:
print("# de preguntas:", preguntas['Pregunta'].nunique())
preguntas.tail()

# de preguntas: 156

,Código variable standard,Código variable ARG (Nº de pregunta),Pregunta,Códigos de respuesta,Etiquetas de respuesta
860,qnpe5g,q72,Porcentaje de estudiantes que asistieron a cla...,2.0,No
861,qnpe5g,q72,Porcentaje de estudiantes que asistieron a cla...,NaN,Dato perdido
862,weight,q72,PESO,NaN,NaN
864,stratum,q72,ESTRATO,NaN,NaN
866,psu,q72,PSU,NaN,NaN

In [86]:
# Creamos un mapa para poder traducir el codigo de una pregunta facilmente al lenguaje natural.
codigo_preguntas = preguntas[["Código variable standard", "Pregunta"]].drop_duplicates()
traducciones = dict(zip(codigo_preguntas["Código variable standard"], codigo_preguntas["Pregunta"]))
print(str(traducciones)[:250], "... }")

{'q1': '¿Qué edad tienes?', 'q2': '¿Cuál es tu sexo?', 'q3': '¿En qué grado o año estás?', 'q4': '¿Cuál es tu estatura, sin zapatos? (Nota: dato en metros)', 'q5': '¿Cuánto pesas, sin zapatos?  (Nota: dato en kilogramos.)', 'q6': 'Durante los últimos ... }